version: "3.8"

services:
  pg_trunk:
    image: pg_trunk
    container_name: pg_trunk
    build:
      context: .
      target: application
    volumes:
      - ".:/pg_trunk"
      - ".data/root:/root"
    ports:
        - "3500:3500"
    tty: true
    depends_on:
      - postgres
    restart: unless-stopped

  nginx:
    image: nginx:1.21.5
    container_name: pg_trunk_nginx
    ports:
      - "8000:80"
    volumes:
      - "./conf/nginx.conf:/etc/nginx/conf.d/default.conf"
    restart: unless-stopped

  postgres:
    image: postgres:14.1
    container_name: pg_trunk_postgres
    volumes:
      - ".data/db:/var/lib/postgresql/data"
    command: postgres -c shared_preload_libraries=pg_stat_statements
    environment:
      - POSTGRES_DB=trunk
      - POSTGRES_USER=trunk
      - POSTGRES_PASSWORD=trunk
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready --quiet || exit 1"]
      interval: 1m
      timeout: 30s
      retries: 10
      start_period: 40s
    restart: unless-stopped
